class Global_Vars:
    model = []
    UNET_PATH = []
    Images = []
    Data = []
    Feat = []
    Target = []
    learnperc = None
    Train_Data = []
    Train_Target = []
    Test_Data = []
    Test_Target = []
    Feat_1 = []
    Feat_2 = []
    Feat_3 = []
